# Generated by Django 4.0.5 on 2023-01-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0004_advertise_job_sent_to_user_alter_user_date_graduated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertise',
            old_name='job_sent_to_user',
            new_name='jobs_sents_to_user',
        ),
    ]
