# Generated by Django 4.0.5 on 2023-01-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0005_rename_job_sent_to_user_advertise_jobs_sents_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertise',
            name='jobs_sents_to_user',
        ),
        migrations.AddField(
            model_name='advertise',
            name='user_advertise_list',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
