# Generated by Django 4.0.5 on 2023-01-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0006_remove_advertise_jobs_sents_to_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='job_sent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
