# Generated by Django 4.1.6 on 2023-02-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0008_alter_user_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
